# Generated by Django 3.0.8 on 2020-07-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20200731_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
